name: Python Unit Tests  # Name of the workflow

# Trigger workflow on push or pull request to any branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Define the job that runs the test pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    # Set up the steps for the workflow
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository

      # Step 2: Set up Python 3.10 environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4  # Ensure compatibility with the latest Node.js versions
        with:
          python-version: '3.10'  # Specify the Python version

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run Python unit tests
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests  # Discover and run unit tests from the 'tests' directory

      # Step 5: Upload test results (optional, but useful for tracking)
      - name: Upload test results
        if: always()  # Ensure results are uploaded even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-reports/  # Ensure you generate test reports and store them here
